def generate(
    self,
    prompt: str,
    seed: int,
    height: int,
    width: int,
    num_frames: int,
    frame_rate: float,
    images: list[ImageConditioningInput] | None,
    audio: AudioOrNone,
    camera_motion: str,
    negative_prompt: str,
    tiling_config: TilingConfigType | None,
    resolution: LTXVideoGenResolution | None,
    upscaler: str | None,
) -> Iterator[torch.Tensor] | GenerateVideoResponse:
